services:
  minio:
    image: minio/minio:latest
    container_name: lesson9-files-module-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID:-minioadmin}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY:-minioadmin}
    command: server /data --console-address ":9001"
    ports:
      - "9002:9000"
      - "9001:9001"
    volumes:
      - minio_lesson9_files_module:/data

  minio-init:
    image: minio/mc:latest
    container_name: lesson9-files-module-minio-init
    depends_on:
      - minio
    restart: 'no'
    entrypoint: >
      /bin/sh -c "
      until mc alias set local http://minio:9000 ${AWS_ACCESS_KEY_ID:-minioadmin} ${AWS_SECRET_ACCESS_KEY:-minioadmin}; do
        echo 'waiting for minio...';
        sleep 2;
      done;
      mc mb --ignore-existing local/${AWS_S3_BUCKET:-lesson9-files-private};
      mc anonymous set none local/${AWS_S3_BUCKET:-lesson9-files-private};
      echo 'minio bucket is ready';
      "

volumes:
  minio_lesson9_files_module: